install.packages("cluster", quiet= T)
install.packages("BiocManager", quiet= T)
install.packages("rockchalk", quiet= T)
BiocManager::install("limma", quiet= T)
BiocManager::install("GEOquery", quiet= T)
install.packages("gmp", quiet = T)
install.packages("Rmpfr", quiet= T)
BiocManager::install("RankProd", force= T)
install.packages("~/GEOPythia_1.00_R_x86_64-pc-linux-gnu.tar.gz")
